name: job-scrapy

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: job_user
      MONGO_INITDB_ROOT_PASSWORD: job_password
      MONGO_INITDB_DATABASE: job_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db:rw
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
