[project]
name = "restaurant-scrapy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "scrapy>=2.12.0",
    "scrapy-selenium>=0.0.7",
    "selenium==4.10.0",
    "webdriver-manager>=4.0.2",
]
